<?php ?><!doctype html>
<html lang="sw">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ramani Majengo — GIS & Survey Workspace</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://unpkg.com/maplibre-gl@5.6.1/dist/maplibre-gl.css" rel="stylesheet">
<style>
:root{--ink:#20251f;--muted:#6b7368;--paper:#fffdf9;--cream:#f3efe7;--green:#53664d;--line:#ded8cd}
*{box-sizing:border-box}html,body{margin:0;height:100%;background:var(--cream);color:var(--ink);font-family:Arial,sans-serif}.top{height:64px;background:var(--paper);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 18px;position:relative;z-index:20}.brand{font-weight:800;letter-spacing:.08em}.tools{display:flex;gap:8px;flex-wrap:wrap}.btnx{border:1px solid #cfc8bb;background:#fff;padding:9px 13px;font-weight:700}.btnx.primary{background:var(--green);color:#fff;border-color:var(--green)}.workspace{height:calc(100vh - 64px);display:grid;grid-template-columns:310px 1fr 330px;min-height:600px}.side{background:var(--paper);overflow:auto;padding:18px;border-right:1px solid var(--line);z-index:5}.right{border-right:0;border-left:1px solid var(--line)}.map{position:relative;min-width:0}.mapbox{position:absolute;inset:0}.panel{border:1px solid var(--line);background:#fff;padding:15px;margin-bottom:14px}.panel h6{font-weight:800;text-transform:uppercase;letter-spacing:.08em;font-size:11px;color:var(--green)}.metric{font-size:25px;font-weight:800}.muted{font-size:12px;color:var(--muted);line-height:1.6}.status{padding:10px;background:#edf1eb;font-size:12px}.coord{font-family:monospace;font-size:12px;word-break:break-all}.legend{display:flex;gap:8px;align-items:center;font-size:12px;margin:7px 0}.dot{width:12px;height:12px;background:var(--green);display:inline-block}.dot.blue{background:#3478b8}.dot.gold{background:#b78b3c}.map-hint{position:absolute;left:18px;top:18px;background:rgba(255,253,249,.94);padding:12px 15px;box-shadow:0 5px 25px #0002;z-index:4;max-width:360px;font-size:12px}.mode{font-size:12px;font-weight:800}.table-mini{width:100%;font-size:11px}.table-mini td{padding:4px;border-bottom:1px solid #eee}.canvas2d{width:100%;height:260px;border:1px solid var(--line);background:#faf9f5}.feature-card{padding:11px;border:1px solid var(--line);margin-bottom:8px}.feature-card strong{display:block}.badge-soft{background:#edf1eb;padding:4px 7px;font-size:10px;font-weight:700}.webgpu{font-size:11px}.footer-note{font-size:10px;color:#7b8278;margin-top:12px}
@media(max-width:1050px){.workspace{grid-template-columns:260px 1fr}.right{display:none}}@media(max-width:700px){.top{height:auto;min-height:64px;align-items:flex-start;padding:12px;gap:10px;flex-direction:column}.workspace{height:calc(100vh - 110px);grid-template-columns:1fr}.side{display:none}.map-hint{max-width:280px}}
</style>
</head>
<body>
<header class="top"><div class="brand">RM · GIS / SURVEY / 3D</div><div class="tools"><button class="btnx primary" id="drawBtn">Draw plot</button><button class="btnx" id="finishBtn">Finish</button><button class="btnx" id="clearBtn">Clear</button><button class="btnx" id="exportBtn">Export GeoJSON</button><a class="btnx text-decoration-none" href="index.php">AI Planner</a></div></header>
<div class="workspace">
<aside class="side">
<div class="panel"><h6>Survey workspace</h6><div class="metric" id="area">0.00 m²</div><div class="muted">Live polygon area</div><hr><div class="metric" id="perimeter">0.00 m</div><div class="muted">Perimeter</div></div>
<div class="panel"><h6>Technology layer</h6><div class="feature-card"><strong>C++</strong><span class="muted">3D geometry, rendering and high-performance spatial engine.</span></div><div class="feature-card"><strong>Python</strong><span class="muted">GIS, AI, automation, geometry and engineering calculations.</span></div><div class="feature-card"><strong>TypeScript / JavaScript</strong><span class="muted">Browser map, CAD-style interaction and application UI.</span></div><div class="feature-card"><strong>PostgreSQL + PostGIS</strong><span class="muted">Target spatial database for coordinates, parcels, roads and buildings.</span></div><div class="feature-card"><strong>WebGL / WebGPU</strong><span class="muted">Browser GPU layer for interactive 2D/3D visualization.</span></div><div class="feature-card"><strong>OpenGL / Vulkan</strong><span class="muted">Future native high-performance rendering engine.</span></div></div>
<div class="panel"><h6>Survey points</h6><table class="table-mini"><tbody id="points"><tr><td colspan="3" class="muted">Click Draw plot, then click the map.</td></tr></tbody></table></div>
</aside>
<main class="map"><div id="map" class="mapbox"></div><div class="map-hint"><b id="modeText">Map ready.</b><br><span>Draw plot → click boundary points → Finish. Double-click also finishes.</span></div></main>
<aside class="side right">
<div class="panel"><h6>Map data</h6><div class="status" id="mapStatus">OpenStreetMap base map · MapLibre WebGL</div><div class="mt-2 coord" id="cursor">Move over map for coordinates.</div></div>
<div class="panel"><h6>3D / GPU</h6><div class="status" id="gpuStatus">Checking WebGPU…</div><div class="muted mt-2">The map renderer uses WebGL now. WebGPU capability is detected for the next high-performance 3D engine layer.</div></div>
<div class="panel"><h6>Plot geometry</h6><canvas id="plan2d" class="canvas2d" width="600" height="300"></canvas><div class="muted mt-2">This preview is generated from the same surveyed polygon. It is the foundation for connecting the AI house plan to the real site.</div></div>
<div class="panel"><h6>Next engineering layers</h6><div class="legend"><span class="dot"></span> Plot / parcel</div><div class="legend"><span class="dot blue"></span> Building footprint</div><div class="legend"><span class="dot gold"></span> Survey / control point</div><div class="footer-note">Preliminary GIS/survey visualization only. Professional boundary survey, structural design and construction documents require qualified professionals.</div></div>
</aside>
</div>
<script src="https://unpkg.com/maplibre-gl@5.6.1/dist/maplibre-gl.js"></script>
<script>
const map=new maplibregl.Map({container:'map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[34.8,-6.16],zoom:6});
map.addControl(new maplibregl.NavigationControl(),'top-right');
let drawing=false,points=[],finished=false;
const sourceId='plot-source';
function geo(){return {type:'FeatureCollection',features:[{type:'Feature',properties:{kind:'plot'},geometry:{type:'Polygon',coordinates:[points.concat(points.length? [points[0]]:[])]}}]};}
function lineGeo(){return {type:'Feature',properties:{},geometry:{type:'LineString',coordinates:points}};}
function refresh(){
 const feats=[]; if(points.length>1)feats.push({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:points}}); if(points.length>=3&&finished)feats.push({type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[...points,points[0]]]}});
 const s=map.getSource(sourceId); if(s)s.setData({type:'FeatureCollection',features:feats});
 points.forEach((p,i)=>{if(!map.getSource('p'+i)){map.addSource('p'+i,{type:'geojson',data:{type:'Feature',properties:{},geometry:{type:'Point',coordinates:p}}});map.addLayer({id:'p'+i,type:'circle',source:'p'+i,paint:{'circle-radius':5,'circle-color':'#b78b3c','circle-stroke-color':'#fff','circle-stroke-width':2}})}else map.getSource('p'+i).setData({type:'Feature',properties:{},geometry:{type:'Point',coordinates:p}})});
 if(points.length>=3&&finished){let a=0,p=0;for(let i=0;i<points.length;i++){let j=(i+1)%points.length;let [lon1,lat1]=points[i],[lon2,lat2]=points[j];let dx=(lon2-lon1)*111320*Math.cos((lat1+lat2)*Math.PI/360),dy=(lat2-lat1)*110540;p+=Math.hypot(dx,dy);a+=lon1*lat2-lon2*lat1;}a=Math.abs(a)/2*111320*110540*Math.cos((points.reduce((s,x)=>s+x[1],0)/points.length)*Math.PI/180);document.getElementById('area').textContent=a.toFixed(2)+' m²';document.getElementById('perimeter').textContent=p.toFixed(2)+' m';draw2d();}else{document.getElementById('area').textContent='0.00 m²';document.getElementById('perimeter').textContent='0.00 m';draw2d();}
 document.getElementById('points').innerHTML=points.length?points.map((p,i)=>`<tr><td>P${i+1}</td><td>${p[1].toFixed(6)}</td><td>${p[0].toFixed(6)}</td></tr>`).join(''):'<tr><td colspan="3" class="muted">No points yet.</td></tr>';
}
function finish(){if(points.length<3){alert('Add at least 3 boundary points.');return}finished=true;drawing=false;document.getElementById('modeText').textContent='Plot completed.';refresh();save();}
function save(){localStorage.setItem('ramani-majengo-plot',JSON.stringify(points));}
function load(){try{points=JSON.parse(localStorage.getItem('ramani-majengo-plot')||'[]');if(points.length>=3)finished=true;}catch(e){} }
function draw2d(){const c=document.getElementById('plan2d'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#faf9f5';x.fillRect(0,0,c.width,c.height);if(!points.length)return;let xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),pad=35,sx=(c.width-pad*2)/Math.max(maxx-minx,.000001),sy=(c.height-pad*2)/Math.max(maxy-miny,.000001),s=Math.min(sx,sy);const xy=p=>[pad+(p[0]-minx)*s,c.height-pad-(p[1]-miny)*s];x.beginPath();points.forEach((p,i)=>{let q=xy(p);i?x.lineTo(q[0],q[1]):x.moveTo(q[0],q[1])});if(finished)x.closePath();x.fillStyle='#e7eee3';x.fill();x.strokeStyle='#53664d';x.lineWidth=3;x.stroke();points.forEach((p,i)=>{let q=xy(p);x.fillStyle='#b78b3c';x.beginPath();x.arc(q[0],q[1],5,0,Math.PI*2);x.fill();x.fillStyle='#20251f';x.font='11px Arial';x.fillText('P'+(i+1),q[0]+7,q[1]-7)});}
map.on('load',()=>{map.addSource(sourceId,{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'plot-fill',type:'fill',source:sourceId,filter:['==','$type','Polygon'],paint:{'fill-color':'#53664d','fill-opacity':.22}});map.addLayer({id:'plot-line',type:'line',source:sourceId,paint:{'line-color':'#53664d','line-width':3}});load();refresh();});
map.on('click',e=>{if(!drawing)return;points.push([e.lngLat.lng,e.lngLat.lat]);finished=false;document.getElementById('modeText').textContent='Point '+points.length+' added — keep drawing or Finish.';refresh();});
map.on('dblclick',e=>{e.preventDefault();if(drawing)finish();});
map.on('mousemove',e=>document.getElementById('cursor').textContent=e.lngLat.lat.toFixed(6)+', '+e.lngLat.lng.toFixed(6));
document.getElementById('drawBtn').onclick=()=>{drawing=true;finished=false;points=[];for(let i=0;i<50;i++){if(map.getLayer('p'+i))map.removeLayer('p'+i);if(map.getSource('p'+i))map.removeSource('p'+i);}document.getElementById('modeText').textContent='Drawing mode — click the plot boundary.';refresh();};
document.getElementById('finishBtn').onclick=finish;
document.getElementById('clearBtn').onclick=()=>{points=[];finished=false;drawing=false;localStorage.removeItem('ramani-majengo-plot');for(let i=0;i<50;i++){if(map.getLayer('p'+i))map.removeLayer('p'+i);if(map.getSource('p'+i))map.removeSource('p'+i);}document.getElementById('modeText').textContent='Map ready.';refresh();};
document.getElementById('exportBtn').onclick=()=>{if(points.length<3){alert('Draw a plot first.');return}let data={type:'FeatureCollection',features:[{type:'Feature',properties:{source:'Ramani Majengo',type:'survey_plot'},geometry:{type:'Polygon',coordinates:[[...points,points[0]]]}}]};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/geo+json'}));a.download='ramani-majengo-plot.geojson';a.click();};
if('gpu' in navigator)navigator.gpu.requestAdapter().then(a=>document.getElementById('gpuStatus').textContent=a?'WebGPU adapter detected — ready for future 3D engine.':'WebGPU unavailable; WebGL remains active.').catch(()=>document.getElementById('gpuStatus').textContent='WebGPU permission/adapter unavailable; WebGL remains active.');else document.getElementById('gpuStatus').textContent='WebGPU not exposed by this browser; WebGL remains active.';
</script>
</body></html>