<?php
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
function out($ok,$message='',$extra=[]){http_response_code($ok?200:400);echo json_encode(array_merge(['ok'=>$ok,'message'=>$message],$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if($_SERVER['REQUEST_METHOD']!=='POST') out(false,'POST only');
$data=json_decode(file_get_contents('php://input'),true);if(!is_array($data)) out(false,'Invalid JSON.');
$plotW=(float)($data['plot_width']??0);$plotD=(float)($data['plot_depth']??0);if($plotW<=0||$plotD<=0) out(false,'Weka upana na urefu wa kiwanja kwa mita.');
$brief=trim((string)($data['brief']??$data['notes']??''));if($brief==='')out(false,'Andika maelezo ya nyumba unayotaka ili AI iweze kupanga spaces.');
$input=['project'=>trim((string)($data['project']??'House Project')),'client'=>trim((string)($data['client']??'')),'contact'=>trim((string)($data['contact']??'')),'location'=>trim((string)($data['location']??'')),'plot_width'=>$plotW,'plot_depth'=>$plotD,'road_side'=>(string)($data['road_side']??'North'),'style'=>trim((string)($data['style']??'')),'brief'=>$brief];
$key=getenv('OPENAI_API_KEY');
if(!$key && is_file(__DIR__.'/openai-config.php')) $key=trim((string)require __DIR__.'/openai-config.php');
if(!$key)out(false,'AI service haijaunganishwa kwa sasa. Weka OPENAI_API_KEY kwenye server.');
$system='You are a serious architectural space-planning assistant for preliminary residential concepts. The client intentionally does NOT provide a room list and does NOT want an interview-style questionnaire. Read the natural-language brief and infer the house function, bedrooms, bathrooms, living spaces, service spaces, parking and outdoor areas from what the client actually says. If the client does not specify some of these, use sensible architectural assumptions based on the plot size, stated household/use and style. Do NOT ask generic questions such as "How many bedrooms?", "Which additional spaces?", "Should there be parking?", or "What is the intended function?" merely because those details were not explicitly written. Make reasonable professional assumptions and proceed. Only return needs_clarification=true if a critical contradiction or genuinely impossible requirement prevents any sensible concept; never use clarification just to collect optional preferences. If the client says only something broad such as "modern family house", infer a practical family residence with an appropriate number of bedrooms/bathrooms and essential spaces for the given plot, while clearly describing those assumptions in summary. If exact room dimensions are not provided, determine realistic dimensions from function, circulation, plot size, setbacks and the brief. Do not use generic hardcoded dimensions such as 3.5 x 3.5. Do not invent luxury features that the brief does not support, but you may include architecturally necessary circulation/service spaces. The plot dimensions are mandatory and must be respected. Create a sophisticated, realistic architectural concept, not a generic box. Consider massing, roofline, entrance, facade depth, glazing, materials, veranda/terrace, parking, garden and outdoor circulation when justified. Keep the exterior concept consistent with the floor-plan concept. Use metric units. Return ONLY valid JSON with exactly these keys: needs_clarification, questions, title, summary, house_width, house_depth, measurements, room_experience, outside_preview, rooms. questions is an array of strings and should normally be empty because you should infer missing details. rooms is an array of objects with name,width,depth. If needs_clarification=true, questions may be populated and rooms may be empty. If false, rooms must contain the spaces inferred from the brief. This is preliminary planning, not structural engineering, permit approval or final construction documentation.';
$user='CLIENT BRIEF:\n'.json_encode($input,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);
$body=json_encode(['model'=>'gpt-5.6-luna','input'=>[['role'=>'system','content'=>$system],['role'=>'user','content'=>$user]],'max_output_tokens'=>5000],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
$ch=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>60,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Authorization: Bearer '.$key],CURLOPT_POSTFIELDS=>$body]);$res=curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);
if($res===false||$http<200||$http>=300)out(false,'AI service haikupatikana kwa sasa. Jaribu tena baada ya muda.',['detail'=>$err?:'HTTP '.$http]);
$j=json_decode($res,true);$text=$j['output_text']??'';if(!$text&&isset($j['output']))foreach($j['output'] as $item)foreach(($item['content']??[]) as $c)if(isset($c['text']))$text.=$c['text'];$text=trim($text);$text=preg_replace('/^```(?:json)?\s*|\s*```$/i','',$text);$plan=json_decode($text,true);if(!is_array($plan))out(false,'AI ilirudisha jibu lisiloweza kusomeka. Jaribu tena.');
$plan['needs_clarification']=(bool)($plan['needs_clarification']??false);$plan['questions']=array_values(array_filter((array)($plan['questions']??[]),fn($q)=>trim((string)$q)!==''));
if($plan['needs_clarification'])out(true,'AI inahitaji maelezo machache zaidi.',['plan'=>$plan,'ai'=>true]);
if(empty($plan['rooms'])||!is_array($plan['rooms']))out(false,'AI haikuweza kutambua spaces kutoka kwenye maelezo. Ongeza maelezo kidogo zaidi kuhusu matumizi ya nyumba.');
$normalized=[];foreach(array_slice($plan['rooms'],0,40) as $r){$name=trim((string)($r['name']??''));if($name==='')continue;$w=(float)($r['width']??0);$d=(float)($r['depth']??0);if($w<=0||$d<=0)continue;$normalized[]=['name'=>$name,'width'=>round($w,2),'depth'=>round($d,2)];}if(!$normalized)out(false,'AI haikuweza kutoa vipimo halali vya spaces. Jaribu tena.');
$plan['rooms']=$normalized;$plan['house_width']=(float)($plan['house_width']??min($plotW-1,$plotW));$plan['house_depth']=(float)($plan['house_depth']??min($plotD-1,$plotD));$plan['title']=(string)($plan['title']??$input['project']);out(true,'AI concept generated.',['plan'=>$plan,'ai'=>true]);
